// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// spa_toggle //
// ---------- //

#define spa_toggle_wrap_target 0
#define spa_toggle_wrap 8

static const uint16_t spa_toggle_program_instructions[] = {
            //     .wrap_target
    0xe040, //  0: set    y, 0                       
    0x80a0, //  1: pull   block                      
    0x6f04, //  2: out    pins, 4                [15]
    0x6004, //  3: out    pins, 4                    
    0x6050, //  4: out    y, 16                      
    0x0085, //  5: jmp    y--, 5                     
    0x6f04, //  6: out    pins, 4                [15]
    0x6004, //  7: out    pins, 4                    
    0x0000, //  8: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spa_toggle_program = {
    .instructions = spa_toggle_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config spa_toggle_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spa_toggle_wrap_target, offset + spa_toggle_wrap);
    return c;
}
#endif
